config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :clubs
  resources :profiles
  delete 'users/:id', to: 'users#destroy', as: :admin_destroy_user


  devise_for :users, path: 'auth',
    controllers:{
      confirmations: 'confirmations'
  },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: 'register',
      sign_up: 'cmon_let_me_in',
    }

  devise_scope :user do
    delete 'auth/logout', to: 'devise/sessions#destroy'
  end

  root 'pages#home'
  post "section_enroll", to: "user_sections#create"
  post "club_enroll", to: "user_clubs#create"
  delete "club_cancell", to: "user_clubs#destroy"
  delete "section_cancell", to: "user_sections#destroy"
  resources :users, only: %i[index]
end

app/models/club.rb
class Club < ApplicationRecord
  validates :name, :address, presence: true
  has_many :sections, dependent: :destroy
  has_many :user_clubs
  has_many :users, through: :user_clubs
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]
  before_action :force_profile

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    premium_user?
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    premium_user?
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    premium_user?
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    premium_user?
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      if params[:id]
        @club = Club.find(params[:id])
      else
        redirect_to root_path, notice: "Not found"
      end

    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name, :address)
    end

    def force_profile
        if(current_user && !current_user.profile && current_user.user?)
          redirect_to new_profile_path, notice: "must profile for activity"
        end
    end

end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<% premium_user?  %>
<%= form_with(model: club) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
        <% club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<h1>Clubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= club.address %></td>
        <td><%= link_to 'Show Sections', club %></td>
        <% if current_user && (current_user.admin? || current_user.master?) %>
            <td><%= link_to 'Edit', edit_club_path(club) %></td>
            <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% if current_user && current_user.clubs.include?(club) && current_user.user? %>
                <td><strong>Reserved</td>
                <td><%= link_to "Unfollow", club_cancell_path(club_id: club.id), method: :delete, data: {confirm: "Do you sure?"}   %></td>
        <% else %>
                <td><%= link_to "Follow", club_enroll_path(club_id: club.id), method: :post if current_user && current_user.user? %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && (current_user.admin? || current_user.master?) %>
  <%= link_to 'New Clubs', new_club_path %>
<% end %>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<% if current_user && current_user.profile %>
    <% if @club.sections.present? %>
        <% @club.sections.each do |section| %>
            <div>
                <h3><%= section.name %></h3>
            </div>
            <div>
                <small><%= section.salary %></small>
            </div>
            <div>
                <% if current_user.clubs.include?(@club) %>
                    <% if current_user && current_user.profile && current_user.sections.include?(section) %>
                        <strong>Reserved</strong>
                        <div>
                            <%= link_to "Exit section", section_cancell_path(section_id: section.id), method: :delete  %>
                        </div>
                    <% else %>

                            <%= link_to "Apply", section_enroll_path(section_id: section.id), method: :post %>

                    <% end %>


                <% end %>


            </div>
        <% end %>

    <% end %>

<% end %>