config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :clubs
  resources :profiles
  delete 'users/:id', to: 'users#destroy', as: :admin_destroy_user


  devise_for :users, path: 'auth',
    controllers:{
      confirmations: 'confirmations'
  },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: 'register',
      sign_up: 'cmon_let_me_in',
    }

  devise_scope :user do
    delete 'auth/logout', to: 'devise/sessions#destroy'
  end

  root 'pages#home'
  post "section_enroll", to: "user_sections#create"
  post "club_enroll", to: "user_clubs#create"
  delete "club_cancell", to: "user_clubs#destroy"
  delete "section_cancell", to: "user_sections#destroy"
  resources :users, only: %i[index]
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :user_sections
  has_many :users, through: :user_sections
  validates :name, :salary, presence: true
  belongs_to :club
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :force_profile

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    premium_user?
    @section = Section.new
    @clubs  = Club.all
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    premium_user?
    @section = Section.new(section_params)
    @club  = Club.find_by(name: params[:section][:club_name])
    @section.club  = @club

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    premium_user?
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    premium_user?
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      if params[:id]
        @section ||= Section.find(params[:id])
      else
        redirect_to root_path, notice: "Not found"
      end
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:name, :salary)
    end
    def force_profile
        if( current_user && !current_user.profile && current_user.user?)
          redirect_to new_profile_path, notice: "must profile for activity"
        end
    end


end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<% premium_user? %>
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary %>
  </div>

  <div class="field">
      <%= form.label :club_name %>
      <%= form.text_field :club_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Salary</th>
      <th>Club</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= section.salary %></td>
        <td><%= section.club.name %></td>
        <% if current_user.admin? || current_user.master? %>
            <td><%= link_to 'Show', section %></td>
            <td><%= link_to 'Edit', edit_section_path(section) %></td>
            <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && (current_user.admin? || current_user.master?) %>
  <%= link_to 'New Section', new_section_path %>
<% end %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @section.salary %>
</p>
<% if current_user && (current_user.admin? || current_user.master?) %>
    <%= link_to 'Edit', edit_section_path(@section) %> |
<% end %>