config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :clubs
  resources :profiles
  delete 'users/:id', to: 'users#destroy', as: :admin_destroy_user


  devise_for :users, path: 'auth',
    controllers:{
      confirmations: 'confirmations'
  },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: 'register',
      sign_up: 'cmon_let_me_in',
    }

  devise_scope :user do
    delete 'auth/logout', to: 'devise/sessions#destroy'
  end

  root 'pages#home'
  post "section_enroll", to: "user_sections#create"
  post "club_enroll", to: "user_clubs#create"
  delete "club_cancell", to: "user_clubs#destroy"
  delete "section_cancell", to: "user_sections#destroy"
  resources :users, only: %i[index]
end

app/views/layouts/_admin.html.erb
<% if current_user && current_user.admin?  %>
    <div>
        <strong>Admin</strong>
    </div>
    <div>
        <%= link_to "Users", users_path %>
        <%= link_to "Clubs", clubs_path %>
        <%= link_to "Sections", sections_path %>
        <%= link_to "Signout", destroy_user_session_path, method: :delete %>
    </div>
<% end %>

app/views/layouts/_alert.html.erb
<div class="notification is-warning">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_header.html.erb
<%= render "layouts/user" %>
<%= render "layouts/admin" %>
<%= render "layouts/master" %>

app/views/layouts/_master.html.erb
<% if current_user && current_user.master?  %>
    <div>
        <strong>Master</strong>
    </div>
    <div>
        <%= link_to "Clubs", clubs_path %>
        <%= link_to "Sections", sections_path %>
        <%= link_to "Signout", destroy_user_session_path, method: :delete %>
    </div>
<% end %>

app/views/layouts/_user.html.erb
<div>
    <% if current_user && current_user.user? %>
        <div>
            <strong>User:<small><%= current_user.profile.present? ? current_user.profile.firstname : current_user.email %></small>
        </div>
        <div>
            <%= link_to "Signout", destroy_user_session_path, method: :delete %>
            <%= link_to "EditAccount", edit_user_registration_path %>
            <% if current_user && current_user.user? %>
                <%=  link_to "Profile", edit_profile_path(current_user.profile) if current_user.profile %>
            <% end %>
            <%= link_to "ReservedClub", clubs_path if current_user.user? %>
            <%= link_to "Sections", sections_path if current_user.user? %>
            <div>
                <section>

                    <% current_user.sections.each do |section| %>
                        <header><h4><%= section.club.name %></h4></header>
                        <div>
                            <strong>Name:<%= section.name %></strong>
                        </div>
                        <div>
                            <footer>
                                <small>Salary:<%= section.salary %></small>
                            </footer>
                        </div>
                    <% end %>

                </section>
            </div>

    <% else %>
            <% if !current_user ||  current_user.user? %>
                <%= link_to "Signup", new_user_registration_path %>
                <%= link_to "Signin", user_session_path %>
                <%= link_to "Clubs", clubs_path %>
            <% end %>

    <% end %>

        </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ariana</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>